apiVersion: v1
kind: Pod
metadata:
  name: init-containers
spec:
  containers:
  - name: main-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: init-service
    image: busybox:1.28
    command:
     - /bin/sh
     - -c
     - wget -O index.html https://google.com/index.html
