apiVersion: v1
kind: Pod
metadata:
  name: probe-readiness-tcp
spec:
  containers:
  - name: probe-readiness-tcp
    image: k8s.gcr.io/goproxy:0.1
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 60

